package com.team.study;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/**
 * 生成测试图片（手动运行，用于测试图片上传+RAG）
 */
public class GenerateTestImage {

    public static void main(String[] args) throws IOException {
        int width = 600, height = 400;
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = image.createGraphics();

        // 白色背景
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, width, height);

        // 绘制文字
        g.setColor(Color.BLACK);
        g.setFont(new Font("Arial", Font.BOLD, 28));
        g.drawString("RevMate Smart Learning", 50, 80);

        g.setFont(new Font("Arial", Font.PLAIN, 20));
        g.drawString("This is a test image for OCR.", 50, 140);
        g.drawString("RAG stands for Retrieval-Augmented Generation.", 50, 180);
        g.drawString("Spring AI is a Java AI framework.", 50, 220);
        g.drawString("POKERBENCH is a benchmark for LLMs.", 50, 260);

        g.setFont(new Font("Arial", Font.ITALIC, 16));
        g.drawString("Generated by RevMate - 2026", 180, 340);

        g.dispose();

        File output = new File("test-ocr.png");
        ImageIO.write(image, "png", output);
        System.out.println("测试图片已生成: " + output.getAbsolutePath());
    }
}
