spring:
  datasource:
    url: jdbc:mysql://localhost:3306/revmate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false

  jpa:
